### ISSUE TITLE
Convert pdf to html fail.: null

### ISSUE THREAD

**Issue by lpla** [bitextor/pdf-extract#15]
Test with this PDF: http://abclys.com/wp-content/uploads/2014/10/Prisliste-med-nye-navne-pr-14.10.14.pdf

Result:

```
java -jar pdf-extract/runnable-jar/PDFExtract.jar -I ~/Downloads/Prisliste-med-nye-navne-pr-14.10.14.pdf -O test.asdf
File: /home/lpla/Downloads/Prisliste-med-nye-navne-pr-14.10.14.pdf, Start extract
File: /home/lpla/Downloads/Prisliste-med-nye-navne-pr-14.10.14.pdf, Extract fail: Convert pdf to html fail.: null
```

**Comment by dionwiggins** [comment]
Hi Leo,

We traced this one and it is occurring in the apache PDFBox library. We will dig in a bit further, but this may be too deep for us to resolve.

java.lang.UnsupportedOperationException
	at org.apache.pdfbox.pdmodel.graphics.color.PDPattern.toRGB(PDPattern.java:95)
	at org.fit.pdfdom.PathDrawer.pdfColorToColor(PathDrawer.java:133)
	at org.fit.pdfdom.PathDrawer.clearPathGraphics(PathDrawer.java:79)
	at org.fit.pdfdom.PathDrawer.drawPath(PathDrawer.java:59)
	at org.fit.pdfdom.PDFDomTree.createPathImage(PDFDomTree.java:403)
	at org.fit.pdfdom.PDFDomTree.renderPath(PDFDomTree.java:251)
	at org.fit.pdfdom.PDFBoxTree.processOperator(PDFBoxTree.java:499)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:505)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:479)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:152)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:139)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391)
	at org.fit.pdfdom.PDFBoxTree.processPage(PDFBoxTree.java:208)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
	at org.fit.pdfdom.PDFDomTree.createDOM(PDFDomTree.java:218)
	at pdfextract.PDFExtract.convertPdfToHtml(PDFExtract.java:560)
	at pdfextract.PDFExtract.Extract(PDFExtract.java:233)
	at Main.main(Main.java:68)

**Comment by dionwiggins** [comment]
This has been addressed as agreed by putting an error handler into the tool to trap the error when it occurs in PDFBox and reporting the error message and the stack trace in the XML output. While not a total solution, working on PDFBox to resolve is out of scope for now. Handling the error gracefully on the rare occasion that it occurs is the current workaround. Will close based on this.
